language: python
dist: xenial

python:
- '3.6'
- '3.7'
- '3.8'

env:
- DJANGO_VERSION=2.0.*
- DJANGO_VERSION=2.1.*
- DJANGO_VERSION=2.2.*
- DJANGO_VERSION=3.0.*

script:
- pip install codecov
- pip install -q django==$DJANGO_VERSION
- pip install -e '.[test]'
- coverage run setup.py test
- coverage report -m --fail-under=85
- flake8
- isort --check-only

after_success:
- codecov

deploy:
  provider: pypi
  user: kingbuzzman
  password:
    secure: Il6rA5fvq5icVtvOTjHyzmMa5qJJx8NkUguzJLOZQMvDrxup4Ey4Wu0Gfv1PmtGzdGP+hGv7eA3A8lj09dSvW4TYvH69n403T97MB3jKWiXlw/JEJKUetzegcyY7IjynI5czlRxfgGpV9BkrqNxb1aiuEv2Rbl9p5TI+9zdhKk5daNJkVlyFX3MD9xplJNZonfUTG/RKkRnZs8iLXuO8x5SBqB8sfq9OjO5kS4F7IvcV8TJUH3hk7xFoDrKFbGTjibLB8VQMf6M4VHLe6do+BfaaWiAYzAMtkZaAxQY8otK5uO9NatPKtrqTQaCG3+dsnilQPY8spabgagxxAxSjcnkEWWC4KO0AtKZGYGKybsq9bNlh2BLdWRNdHPE2xZJp0PHoTpPOVykz35/iMfLoeKbAe77QBwOetzYI5OvP/hSuvtF/PRyXdYHLnXtYpBqRhKgdLj26yNvVLB75P+R1g4BQ1tyqidO8hYqGRdvv76w3PMG9YAR8yfVAaltfX/c+G3bt0A77YbIAXBA2Im+TdxXWademEl1wShINKWkb42Ewy8BwhvJhhGG7t3LAbPlnwrZ281h0xJFHgx+OoD2Qix5b1ngRyBkoS5aiA6JFhNDe3MbHhV6zgj6JGTCpv3Nttd22hmAyvBdR/N9xKi+WgfylQAuucJybUNHKQQdAxFI=
  on:
    branch: master
